/* PgluAI built-in self-test question bank.
   Structure: QUIZ_BANK[classBand][subject] = [ { q, options[4], answer (index) }, ... ] */
const QUIZ_BANK = {
  "Nursery–UKG": {
    "General Knowledge": [
      { q: "Which animal says \"Moo\"?", options: ["Cat", "Cow", "Dog", "Duck"], answer: 1 },
      { q: "What colour is the sky on a clear day?", options: ["Green", "Blue", "Red", "Black"], answer: 1 },
      { q: "How many days are there in a week?", options: ["5", "6", "7", "8"], answer: 2 },
      { q: "Which fruit is yellow and long?", options: ["Apple", "Banana", "Grapes", "Orange"], answer: 1 },
      { q: "Where do fish live?", options: ["Trees", "Water", "Sky", "Sand"], answer: 1 },
      { q: "What do we use to see?", options: ["Ears", "Eyes", "Nose", "Hands"], answer: 1 },
      { q: "Which is a wild animal?", options: ["Cow", "Lion", "Goat", "Dog"], answer: 1 },
      { q: "What do bees make?", options: ["Milk", "Honey", "Bread", "Juice"], answer: 1 },
      { q: "Which season is the hottest?", options: ["Winter", "Summer", "Rainy", "Spring"], answer: 1 },
      { q: "What do we use to write?", options: ["Spoon", "Pencil", "Cup", "Shoe"], answer: 1 },
    ],
    "Maths": [
      { q: "How many fingers are there on one hand?", options: ["3", "4", "5", "6"], answer: 2 },
      { q: "What comes after 2?", options: ["1", "3", "4", "5"], answer: 1 },
      { q: "1 + 1 = ?", options: ["1", "2", "3", "4"], answer: 1 },
      { q: "Which number is the biggest?", options: ["1", "5", "9", "3"], answer: 2 },
      { q: "Which shape has 3 sides?", options: ["Circle", "Square", "Triangle", "Star"], answer: 2 },
      { q: "2 + 2 = ?", options: ["3", "4", "5", "6"], answer: 1 },
      { q: "How many wheels does a bicycle have?", options: ["1", "2", "3", "4"], answer: 1 },
      { q: "What comes before 5?", options: ["3", "4", "6", "7"], answer: 1 },
      { q: "Which number is the smallest?", options: ["7", "2", "9", "5"], answer: 1 },
      { q: "3 + 1 = ?", options: ["2", "3", "4", "5"], answer: 2 },
    ],
  },
  "Class 1–5": {
    "Maths": [
      { q: "7 + 8 = ?", options: ["14", "15", "16", "13"], answer: 1 },
      { q: "9 × 3 = ?", options: ["27", "24", "21", "18"], answer: 0 },
      { q: "What is half of 20?", options: ["5", "10", "15", "18"], answer: 1 },
      { q: "100 − 45 = ?", options: ["45", "55", "65", "35"], answer: 1 },
      { q: "Which is an even number?", options: ["7", "9", "12", "15"], answer: 2 },
      { q: "How many sides does a square have?", options: ["3", "4", "5", "6"], answer: 1 },
      { q: "12 ÷ 4 = ?", options: ["2", "3", "4", "6"], answer: 1 },
      { q: "What is the place value of 5 in 350?", options: ["5", "50", "500", "5000"], answer: 1 },
      { q: "Which is the largest number?", options: ["234", "243", "432", "342"], answer: 2 },
      { q: "6 × 6 = ?", options: ["30", "36", "42", "12"], answer: 1 },
    ],
    "Science (EVS)": [
      { q: "Which organ helps us breathe?", options: ["Heart", "Lungs", "Stomach", "Liver"], answer: 1 },
      { q: "Plants make food using ___.", options: ["Moonlight", "Sunlight", "Only water", "Only soil"], answer: 1 },
      { q: "Which is a source of light?", options: ["Moon", "Sun", "Mirror", "Cloud"], answer: 1 },
      { q: "How many legs does an insect have?", options: ["4", "6", "8", "10"], answer: 1 },
      { q: "Water freezes into ___.", options: ["Steam", "Ice", "Gas", "Smoke"], answer: 1 },
      { q: "Which animal lays eggs?", options: ["Cow", "Hen", "Dog", "Cat"], answer: 1 },
      { q: "The Sun rises in the ___.", options: ["West", "East", "North", "South"], answer: 1 },
      { q: "Which part of a plant is usually underground?", options: ["Leaf", "Root", "Flower", "Fruit"], answer: 1 },
      { q: "Teeth help us to ___.", options: ["See", "Chew", "Hear", "Walk"], answer: 1 },
      { q: "We should drink water to stay ___.", options: ["Hungry", "Healthy", "Sleepy", "Sad"], answer: 1 },
    ],
    "English": [
      { q: "Which word is a noun?", options: ["Run", "Quickly", "Apple", "Beautiful"], answer: 2 },
      { q: "Plural of \"child\" is?", options: ["Childs", "Children", "Childes", "Childrens"], answer: 1 },
      { q: "Opposite of \"hot\" is?", options: ["Warm", "Cold", "Boiling", "Heat"], answer: 1 },
      { q: "Which word is spelled correctly?", options: ["Frend", "Friend", "Freind", "Frund"], answer: 1 },
      { q: "She ___ to school every day.", options: ["go", "goes", "going", "gone"], answer: 1 },
      { q: "A group of words that makes complete sense is a ___.", options: ["Letter", "Sentence", "Sound", "Page"], answer: 1 },
      { q: "Past tense of \"go\" is?", options: ["Goed", "Went", "Gone", "Going"], answer: 1 },
      { q: "Which letter is a vowel?", options: ["B", "C", "E", "D"], answer: 2 },
      { q: "Opposite of \"happy\" is?", options: ["Glad", "Sad", "Joy", "Smile"], answer: 1 },
      { q: "\"An\" is used before words starting with a ___ sound.", options: ["Consonant", "Vowel", "Number", "Capital"], answer: 1 },
    ],
  },
  "Class 6–8": {
    "Maths": [
      { q: "The approximate value of π is?", options: ["3.14", "2.14", "3.41", "1.34"], answer: 0 },
      { q: "LCM of 4 and 6 is?", options: ["12", "24", "6", "8"], answer: 0 },
      { q: "A right angle measures?", options: ["45°", "90°", "180°", "360°"], answer: 1 },
      { q: "(−3) + (−5) = ?", options: ["−8", "8", "−2", "2"], answer: 0 },
      { q: "3/4 as a decimal is?", options: ["0.75", "0.34", "0.43", "0.7"], answer: 0 },
      { q: "Area of a rectangle = ?", options: ["l + b", "l × b", "2(l + b)", "l²"], answer: 1 },
      { q: "25% of 200 = ?", options: ["25", "50", "75", "100"], answer: 1 },
      { q: "Which is a prime number?", options: ["9", "15", "17", "21"], answer: 2 },
      { q: "HCF of 12 and 18 is?", options: ["6", "12", "18", "3"], answer: 0 },
      { q: "Sum of the angles in a triangle is?", options: ["90°", "180°", "270°", "360°"], answer: 1 },
    ],
    "Science": [
      { q: "Water is made of hydrogen and ___.", options: ["Nitrogen", "Oxygen", "Carbon", "Helium"], answer: 1 },
      { q: "The powerhouse of the cell is?", options: ["Nucleus", "Mitochondria", "Ribosome", "Vacuole"], answer: 1 },
      { q: "The force of attraction towards the Earth is?", options: ["Friction", "Gravity", "Magnetism", "Tension"], answer: 1 },
      { q: "Which gas do plants take in for photosynthesis?", options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"], answer: 1 },
      { q: "The boiling point of water is?", options: ["50°C", "100°C", "0°C", "212°C"], answer: 1 },
      { q: "Which is a good conductor of electricity?", options: ["Wood", "Copper", "Plastic", "Rubber"], answer: 1 },
      { q: "The largest planet in the solar system is?", options: ["Earth", "Jupiter", "Mars", "Saturn"], answer: 1 },
      { q: "Which vitamin do we get from sunlight?", options: ["Vitamin A", "Vitamin D", "Vitamin C", "Vitamin K"], answer: 1 },
      { q: "The basic unit of life is the?", options: ["Atom", "Cell", "Tissue", "Organ"], answer: 1 },
      { q: "Sound cannot travel through?", options: ["Air", "Water", "Vacuum", "Solid"], answer: 2 },
    ],
    "Social Studies": [
      { q: "The Earth's only natural satellite is?", options: ["Sun", "Moon", "Mars", "Venus"], answer: 1 },
      { q: "Who was the first Prime Minister of India?", options: ["Mahatma Gandhi", "Jawaharlal Nehru", "Sardar Patel", "Subhash Bose"], answer: 1 },
      { q: "The longest river in the world is the?", options: ["Amazon", "Nile", "Ganga", "Yangtze"], answer: 1 },
      { q: "How many continents are there?", options: ["5", "6", "7", "8"], answer: 2 },
      { q: "The Taj Mahal is located in?", options: ["Delhi", "Agra", "Jaipur", "Mumbai"], answer: 1 },
      { q: "Which is the largest continent?", options: ["Africa", "Asia", "Europe", "Australia"], answer: 1 },
      { q: "The national animal of India is the?", options: ["Lion", "Tiger", "Elephant", "Peacock"], answer: 1 },
      { q: "Lines drawn east-west on a map are called?", options: ["Longitudes", "Latitudes", "Borders", "Axes"], answer: 1 },
      { q: "The capital of India is?", options: ["Mumbai", "New Delhi", "Kolkata", "Chennai"], answer: 1 },
      { q: "India gained independence in?", options: ["1942", "1947", "1950", "1930"], answer: 1 },
    ],
  },
  "Class 9–10": {
    "Maths": [
      { q: "A quadratic equation has the form?", options: ["ax + b = 0", "ax² + bx + c = 0", "a/x = b", "ax³ = b"], answer: 1 },
      { q: "The value of sin 90° is?", options: ["0", "1", "0.5", "√3/2"], answer: 1 },
      { q: "Sum of the first n natural numbers is?", options: ["n(n + 1)/2", "n²/2", "n(n − 1)", "2n"], answer: 0 },
      { q: "The roots of x² − 5x + 6 = 0 are?", options: ["2 and 3", "1 and 6", "−2 and −3", "5 and 6"], answer: 0 },
      { q: "By Pythagoras theorem, a² + b² = ?", options: ["c", "c²", "2c", "ab"], answer: 1 },
      { q: "Area of a circle is?", options: ["2πr", "πr²", "πd", "πr"], answer: 1 },
      { q: "The discriminant of a quadratic is b² − ?", options: ["4ac", "2ac", "ac", "4a"], answer: 0 },
      { q: "The probability of a sure event is?", options: ["0", "1", "0.5", "100"], answer: 1 },
      { q: "If 2x = 10, then x = ?", options: ["3", "5", "8", "20"], answer: 1 },
      { q: "HCF × LCM of two numbers equals?", options: ["their sum", "their product", "their difference", "their ratio"], answer: 1 },
    ],
    "Science": [
      { q: "The chemical formula of water is?", options: ["CO₂", "H₂O", "O₂", "NaCl"], answer: 1 },
      { q: "Newton's first law is the law of?", options: ["Gravity", "Inertia", "Action", "Energy"], answer: 1 },
      { q: "The unit of electric current is?", options: ["Volt", "Ampere", "Ohm", "Watt"], answer: 1 },
      { q: "A solution with pH less than 7 is?", options: ["Basic", "Acidic", "Neutral", "Salt"], answer: 1 },
      { q: "Cell division that produces gametes is?", options: ["Mitosis", "Meiosis", "Fission", "Fusion"], answer: 1 },
      { q: "The approximate speed of light is?", options: ["3×10⁸ m/s", "3×10⁶ m/s", "3×10⁵ m/s", "3×10¹⁰ m/s"], answer: 0 },
      { q: "Which gas is most abundant in the atmosphere?", options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Argon"], answer: 1 },
      { q: "The functional unit of the kidney is the?", options: ["Neuron", "Nephron", "Alveoli", "Villi"], answer: 1 },
      { q: "Ohm's law states V = ?", options: ["IR", "I/R", "R/I", "I + R"], answer: 0 },
      { q: "The acid present in the stomach is?", options: ["Sulphuric acid", "Hydrochloric acid", "Nitric acid", "Acetic acid"], answer: 1 },
    ],
    "Social Science": [
      { q: "The headquarters of the United Nations is in?", options: ["Geneva", "New York", "Paris", "London"], answer: 1 },
      { q: "The Indian Constitution came into effect on?", options: ["15 Aug 1947", "26 Jan 1950", "26 Nov 1949", "2 Oct 1950"], answer: 1 },
      { q: "The Quit India Movement was launched in?", options: ["1930", "1942", "1947", "1920"], answer: 1 },
      { q: "Which is the highest mountain range?", options: ["Andes", "Himalayas", "Alps", "Rockies"], answer: 1 },
      { q: "Democracy means rule by the?", options: ["King", "People", "Army", "Judges"], answer: 1 },
      { q: "The Reserve Bank of India controls?", options: ["Railways", "Monetary policy", "Defence", "Education"], answer: 1 },
      { q: "The French Revolution began in?", options: ["1789", "1799", "1804", "1750"], answer: 0 },
      { q: "The ozone layer is found in the?", options: ["Troposphere", "Stratosphere", "Mesosphere", "Exosphere"], answer: 1 },
      { q: "The first Battle of Panipat was fought in?", options: ["1526", "1556", "1761", "1600"], answer: 0 },
      { q: "GDP stands for?", options: ["Gross Domestic Product", "General Domestic Price", "Gross Demand Product", "Global Data Plan"], answer: 0 },
    ],
  },
  "Class 11–12": {
    "Physics": [
      { q: "The SI unit of force is?", options: ["Joule", "Newton", "Watt", "Pascal"], answer: 1 },
      { q: "Acceleration due to gravity is approximately?", options: ["9.8 m/s²", "8.9 m/s²", "10.8 m/s²", "6.7 m/s²"], answer: 0 },
      { q: "Work done = Force × ?", options: ["Time", "Displacement", "Mass", "Velocity"], answer: 1 },
      { q: "The unit of power is?", options: ["Newton", "Joule", "Watt", "Ampere"], answer: 2 },
      { q: "Kinetic energy is given by?", options: ["mgh", "½mv²", "mv", "½mv"], answer: 1 },
      { q: "Ohm's law relates V, I and?", options: ["Power", "Resistance", "Charge", "Energy"], answer: 1 },
      { q: "Momentum = mass × ?", options: ["acceleration", "velocity", "force", "time"], answer: 1 },
      { q: "The unit of frequency is?", options: ["Hertz", "Decibel", "Newton", "Joule"], answer: 0 },
      { q: "Which lens converges light?", options: ["Concave", "Convex", "Plane", "Cylindrical"], answer: 1 },
      { q: "The first law of thermodynamics is conservation of?", options: ["Mass", "Energy", "Momentum", "Charge"], answer: 1 },
    ],
    "Chemistry": [
      { q: "The atomic number equals the number of?", options: ["Neutrons", "Protons", "Nucleons", "Molecules"], answer: 1 },
      { q: "The most electronegative element is?", options: ["Oxygen", "Fluorine", "Chlorine", "Nitrogen"], answer: 1 },
      { q: "The pH of a neutral solution is?", options: ["0", "7", "14", "1"], answer: 1 },
      { q: "NaCl is commonly known as?", options: ["Baking soda", "Common salt", "Lime", "Chalk"], answer: 1 },
      { q: "Number of moles = mass / ?", options: ["volume", "molar mass", "density", "pressure"], answer: 1 },
      { q: "Avogadro's number is approximately?", options: ["6.022×10²³", "3×10⁸", "9.8", "1.6×10⁻¹⁹"], answer: 0 },
      { q: "Reaction of an acid with a metal usually releases?", options: ["Oxygen", "Hydrogen", "Carbon dioxide", "Nitrogen"], answer: 1 },
      { q: "The bond in NaCl is?", options: ["Covalent", "Ionic", "Metallic", "Hydrogen"], answer: 1 },
      { q: "The lightest element is?", options: ["Helium", "Hydrogen", "Oxygen", "Lithium"], answer: 1 },
      { q: "Oxidation involves the loss of?", options: ["Protons", "Electrons", "Neutrons", "Energy"], answer: 1 },
    ],
    "Biology": [
      { q: "The basic unit of heredity is the?", options: ["Cell", "Gene", "Tissue", "Atom"], answer: 1 },
      { q: "Photosynthesis occurs in the?", options: ["Mitochondria", "Chloroplast", "Nucleus", "Ribosome"], answer: 1 },
      { q: "DNA stands for?", options: ["Deoxyribonucleic acid", "Diribonucleic acid", "Dual nucleic acid", "Deoxy nucleic atom"], answer: 0 },
      { q: "Humans have how many pairs of chromosomes?", options: ["21", "23", "24", "46"], answer: 1 },
      { q: "The largest organ of the human body is the?", options: ["Heart", "Skin", "Liver", "Lungs"], answer: 1 },
      { q: "Blood is pumped by the?", options: ["Lungs", "Heart", "Liver", "Kidney"], answer: 1 },
      { q: "Which blood cells fight infection?", options: ["Red cells", "White cells", "Platelets", "Plasma"], answer: 1 },
      { q: "Breakdown of glucose to release energy is called?", options: ["Photosynthesis", "Respiration", "Digestion", "Transpiration"], answer: 1 },
      { q: "Insulin is produced by the?", options: ["Liver", "Pancreas", "Kidney", "Stomach"], answer: 1 },
      { q: "The green pigment in plants is?", options: ["Haemoglobin", "Chlorophyll", "Melanin", "Carotene"], answer: 1 },
    ],
    "Maths": [
      { q: "The derivative of x² is?", options: ["2x", "x", "x²/2", "2"], answer: 0 },
      { q: "∫ 1 dx = ?", options: ["x + C", "1", "0", "x²"], answer: 0 },
      { q: "sin²θ + cos²θ = ?", options: ["0", "1", "2", "tan θ"], answer: 1 },
      { q: "log(1) = ?", options: ["0", "1", "10", "undefined"], answer: 0 },
      { q: "The value of 0! is?", options: ["0", "1", "undefined", "10"], answer: 1 },
      { q: "The slope of the line y = mx + c is?", options: ["c", "m", "x", "y"], answer: 1 },
      { q: "The derivative of sin x is?", options: ["cos x", "−cos x", "−sin x", "tan x"], answer: 0 },
      { q: "nCr counts the number of?", options: ["permutations", "combinations", "derivatives", "integrals"], answer: 1 },
      { q: "Sum of an infinite GP (|r| < 1) is?", options: ["a/(1 − r)", "a(1 − r)", "ar", "a + r"], answer: 0 },
      { q: "The value of e is approximately?", options: ["2.718", "3.14", "1.618", "1.414"], answer: 0 },
    ],
  },
};
